trigger:
- main

pool:
  vmImage: 'macOS-latest'

variables:
  workspace: 'EBuyBooks.xcworkspace'
  scheme: 'EBuyBooks'
  configuration: 'Release'
  sdk: 'iphoneos'

steps:

# Checkout repository
- checkout: self
  clean: true

# Install CocoaPods
- script: |
    sudo gem install cocoapods
    pod install
  displayName: 'Install CocoaPods'



# Build Archive
- task: Xcode@5
  displayName: 'Build iOS Application'
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'EBuyBooks.xcworkspace'
    scheme: 'EBuyBooks'
    xcodeVersion: 'default'

    # Package
    packageApp: false

    # Signing
    signingOption: 'nosign'

    # Build destination
    destinationPlatformOption: 'iOS'
    destinationTypeOption: 'simulators'
    destinationSimulators: 'iPhone 16'

    # Advanced
    useXcpretty: true

# Publish IPA
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
